name: Build-SO
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Compile
        run: |
          $ANDROID_HOME/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android30-clang++ \
          -shared -fPIC main.cpp -o libAutoTotem.so
        # Jika folder ndk-bundle tidak ketemu, server akan mencoba folder versi spesifik
        continue-on-error: true

      - name: Compile (Fallback)
        if: steps.compile.outcome == 'failure'
        run: |
          $ANDROID_HOME/ndk/$(ls $ANDROID_HOME/ndk | head -1)/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android30-clang++ \
          -shared -fPIC main.cpp -o libAutoTotem.so

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Mod-Jadi
          path: libAutoTotem.so
