name: Build-AutoSprint-Trigger
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup NDK r25c
        run: |
          wget https://dl.google.com/android/repository/android-ndk-r25c-linux.zip
          unzip -q android-ndk-r25c-linux.zip

      - name: Compile For Vivo Y12
        run: |
          ./android-ndk-r25c/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android30-clang++ \
          -shared -fPIC -O3 -ffast-math \
          main.cpp -o libAutoSprint.so \
          -llog -ldl

      - name: Upload Mod
        uses: actions/upload-artifact@v4
        with:
          name: AutoSprint-Trigger-v1.26
          path: libAutoSprint.so
