name: Build-Ambient-Totem
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup NDK Manual
        run: |
          wget https://dl.google.com/android/repository/android-ndk-r25c-linux.zip
          unzip -q android-ndk-r25c-linux.zip

      - name: Compile Mod for v1.26.13
        run: |
          ./android-ndk-r25c/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android30-clang++ \
          -shared -fPIC -O2 main.cpp -o libAutoTotem.so \
          -llog -ldl

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Ambient-Mod-Jadi
          path: libAutoTotem.so
